version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/postgres_data/
  fastapi:
    build: ./fastapiapp
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - ./fastapiapp:/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  django:
    build: ./djangoapp
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ./djangoapp:/app/
    ports:
      - "3000:3000"
    env_file:
      - ./djangoapp/.env.dev
    depends_on:
      - postgres


volumes:
  postgres_data:
